/**
 * F03 scan callback HMAC verification.
 *
 * The AWS Lambda (ClamAV) signs each callback body with HMAC-SHA256 using
 * SCAN_CALLBACK_SECRET (shared, generated by us — see F03 docs). We verify
 * the signature and a fresh timestamp BEFORE any DB read or write.
 *
 *   Header: X-Muneem-Scan-Sig       (hex-encoded SHA-256)
 *   Header: X-Muneem-Scan-Timestamp (RFC3339 / ISO 8601 UTC)
 *
 * The signed payload is the raw request body bytes, prefixed with the
 * timestamp + a dot, to bind the signature to a moment in time:
 *
 *   sig = HMAC_SHA256(secret, `${timestamp}.${rawBody}`)
 */

import { createHmac, timingSafeEqual } from "node:crypto";

const MAX_SKEW_MS = 5 * 60 * 1000; // 5 minutes

export type VerifyResult =
  | { ok: true }
  | {
      ok: false;
      reason: "missing_secret" | "missing_headers" | "stale" | "bad_signature";
    };

export function getScanCallbackSecret(): string {
  const secret = process.env.SCAN_CALLBACK_SECRET;
  if (!secret || secret.length < 16) {
    throw new Error(
      "SCAN_CALLBACK_SECRET is missing or too short (need ≥16 chars)",
    );
  }
  return secret;
}

export function verifyScanCallback(input: {
  rawBody: string;
  signature: string | null;
  timestamp: string | null;
  now?: Date;
}): VerifyResult {
  let secret: string;
  try {
    secret = getScanCallbackSecret();
  } catch {
    return { ok: false, reason: "missing_secret" };
  }

  if (!input.signature || !input.timestamp) {
    return { ok: false, reason: "missing_headers" };
  }

  const ts = Date.parse(input.timestamp);
  if (Number.isNaN(ts)) {
    return { ok: false, reason: "stale" };
  }
  const now = (input.now ?? new Date()).getTime();
  if (Math.abs(now - ts) > MAX_SKEW_MS) {
    return { ok: false, reason: "stale" };
  }

  const expected = createHmac("sha256", secret)
    .update(`${input.timestamp}.${input.rawBody}`)
    .digest("hex");

  const sigBuf = Buffer.from(input.signature, "hex");
  const expBuf = Buffer.from(expected, "hex");
  if (sigBuf.length !== expBuf.length) {
    return { ok: false, reason: "bad_signature" };
  }
  if (!timingSafeEqual(sigBuf, expBuf)) {
    return { ok: false, reason: "bad_signature" };
  }

  return { ok: true };
}
